### Testing `NodeForecastSolar`

In [19]:
import pandas as pd
from datetime import datetime, timedelta
from eta_utility.connectors.node import NodeForecastSolar
from eta_utility.connectors.forecast_solar import ForecastSolarConnection

from eta_utility.connectors.entso_e import ENTSOEConnection
from eta_utility.connectors.node import NodeEntsoE

from eta_utility.connectors.node import Node

In [20]:
# Display all rows
pd.set_option('display.max_rows', None)

# Display all columns
pd.set_option('display.max_columns', None)

### using `data = watts` (default value)

In [22]:
node_1 = NodeForecastSolar(
    name="east",
    url="https://api.forecast.solar",
    protocol="forecast_solar",
    api_key="87Fpb6aShqa5Hbmf",
    data="watts",
    latitude=49.86381,
    longitude=8.68105,
    declination=[14, 10],
    azimuth=[90, -90],
    kwp=[23.31, 23.31],
)


node_2 = NodeForecastSolar(
    name="east",
    url="https://api.forecast.solar",
    protocol="forecast_solar",
    api_key="87Fpb6aShqa5Hbmf",
    data="watts",
    latitude=49.86381,
    longitude=8.68105,
    declination=[10, 14],
    azimuth=[90, -90],
    kwp=[23.31, 23.31],
)

connector = ForecastSolarConnection(url="https://api.forecast.solar", api_key="87Fpb6aShqa5Hbmf")

nodes = [node_1, node_2]
from_time = datetime.now().replace(hour=0, minute=0, second=0, microsecond=0)
to_time = from_time + timedelta(days=1)
interval = timedelta(minutes=15)

res = connector.read_series(from_time, to_time, nodes, interval)
res

D:\Code Repository\ETA\eta-utility\eta_utility\connectors\forecast_solar.py:147: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  previous_time = from_time.floor("15T") if self._api_key != "None" else from_time.floor("h")
D:\Code Repository\ETA\eta-utility\eta_utility\connectors\forecast_solar.py:154: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  to_time.floor("15T") + timedelta(minutes=15)

                                   east
                                      0             0
2024-11-04 00:00:00+01:00      0.000000      0.000000
2024-11-04 00:15:00+01:00      0.000000      0.000000
2024-11-04 00:30:00+01:00      0.000000      0.000000
2024-11-04 00:45:00+01:00      0.000000      0.000000
2024-11-04 01:00:00+01:00      0.000000      0.000000
2024-11-04 01:15:00+01:00      0.000000      0.000000
2024-11-04 01:30:00+01:00      0.000000      0.000000
2024-11-04 01:45:00+01:00      0.000000      0.000000
2024-11-04 02:00:00+01:00      0.000000      0.000000
2024-11-04 02:15:00+01:00      0.000000      0.000000
2024-11-04 02:30:00+01:00      0.000000      0.000000
2024-11-04 02:45:00+01:00      0.000000      0.000000
2024-11-04 03:00:00+01:00      0.000000      0.000000
2024-11-04 03:15:00+01:00      0.000000      0.000000
2024-11-04 03:30:00+01:00      0.000000      0.000000
2024-11-04 03:45:00+01:00      0.000000      0.000000
2024-11-04 04:00:00+01:00      0.000000      0.000000
2024-11-04 04:15:00+01:00      0.000000      0.000000
2024-11-04 04:30:00+01:00      0.000000      0.000000
2024-11-04 04:45:00+01:00      0.000000      0.000000
2024-11-04 05:00:00+01:00      0.000000      0.000000
2024-11-04 05:15:00+01:00      0.000000      0.000000
2024-11-04 05:30:00+01:00      0.000000      0.000000
2024-11-04 05:45:00+01:00      0.000000      0.000000
2024-11-04 06:00:00+01:00      0.000000      0.000000
2024-11-04 06:15:00+01:00      0.000000      0.000000
2024-11-04 06:30:00+01:00      0.000000      0.000000
2024-11-04 06:45:00+01:00      0.000000      0.000000
2024-11-04 07:00:00+01:00      0.000000      0.000000
2024-11-04 07:15:00+01:00      0.000000      0.000000
2024-11-04 07:30:00+01:00    205.021277    178.340426
2024-11-04 07:45:00+01:00    540.510638    470.170213
2024-11-04 08:00:00+01:00    876.000000    762.000000
2024-11-04 08:15:00+01:00   1631.000000   1425.000000
2024-11-04 08:30:00+01:00   2433.000000   2145.000000
2024-11-04 08:45:00+01:00   3317.000000   2932.000000
2024-11-04 09:00:00+01:00   4011.000000   3556.000000
2024-11-04 09:15:00+01:00   4318.000000   3905.000000
2024-11-04 09:30:00+01:00   4176.000000   3893.000000
2024-11-04 09:45:00+01:00   3942.000000   3781.000000
2024-11-04 10:00:00+01:00   3940.000000   3846.000000
2024-11-04 10:15:00+01:00   4205.000000   4123.000000
2024-11-04 10:30:00+01:00   4509.000000   4414.000000
2024-11-04 10:45:00+01:00   4789.000000   4700.000000
2024-11-04 11:00:00+01:00   5060.000000   4976.000000
2024-11-04 11:15:00+01:00   5349.000000   5268.000000
2024-11-04 11:30:00+01:00   5662.000000   5589.000000
2024-11-04 11:45:00+01:00   5972.000000   5902.000000
2024-11-04 12:00:00+01:00   6220.000000   6164.000000
2024-11-04 12:15:00+01:00   6371.000000   6327.000000
2024-11-04 12:30:00+01:00   6453.000000   6425.000000
2024-11-04 12:45:00+01:00   7658.000000   7629.000000
2024-11-04 13:00:00+01:00  10402.000000  10365.000000
2024-11-04 13:15:00+01:00  11516.000000  11524.000000
2024-11-04 13:30:00+01:00  12580.000000  12651.000000
2024-11-04 13:45:00+01:00  13409.000000  13567.000000
2024-11-04 14:00:00+01:00  13964.000000  14234.000000
2024-11-04 14:15:00+01:00  14177.000000  14565.000000
2024-11-04 14:30:00+01:00  14141.000000  14651.000000
2024-11-04 14:45:00+01:00  13824.000000  14450.000000
2024-11-04 15:00:00+01:00  13256.000000  13959.000000
2024-11-04 15:15:00+01:00  12342.000000  13118.000000
2024-11-04 15:30:00+01:00  11284.000000  12120.000000
2024-11-04 15:45:00+01:00  10156.000000  11043.000000
2024-11-04 16:00:00+01:00   9038.000000   9949.000000
2024-11-04 16:15:00+01:00   8004.000000   8900.000000
2024-11-04 16:30:00+01:00   7025.000000   7877.000000
2024-11-04 16:45:00+01:00   6036.000000   6839.000000
2024-11-04 17:00:00+01:00   4370.000000   4977.000000
2024-11-04 17:15:00+01:00      0.000000      0.000000
2024-11-04 17:30:00+01:00      0.000000      0.000000
2024-11-04 17:45:00+01:00      0.000000      0.000000
2024-11-04 18:00:00+01:00      0.000000      0.000000
2024-11-04 18:15:00+01:00      0.000000      0.000000
2024-11-04 18:30:00+01:00      0.000000      0.000000
2024-11-04 18:45:00+01:00      0.000000      0.000000
2024-11-04 19:00:00+01:00      0.000000      0.000000
2024-11-04 19:15:00+01:00      0.000000      0.000000
2024-11-04 19:30:00+01:00      0.000000      0.000000
2024-11-04 19:45:00+01:00      0.000000      0.000000
2024-11-04 20:00:00+01:00      0.000000      0.000000
2024-11-04 20:15:00+01:00      0.000000      0.000000
2024-11-04 20:30:00+01:00      0.000000      0.000000
2024-11-04 20:45:00+01:00      0.000000      0.000000
2024-11-04 21:00:00+01:00      0.000000      0.000000
2024-11-04 21:15:00+01:00      0.000000      0.000000
2024-11-04 21:30:00+01:00      0.000000      0.000000
2024-11-04 21:45:00+01:00      0.000000      0.000000
2024-11-04 22:00:00+01:00      0.000000      0.000000
2024-11-04 22:15:00+01:00      0.000000      0.000000
2024-11-04 22:30:00+01:00      0.000000      0.000000
2024-11-04 22:45:00+01:00      0.000000      0.000000
2024-11-04 23:00:00+01:00      0.000000      0.000000
2024-11-04 23:15:00+01:00      0.000000      0.000000
2024-11-04 23:30:00+01:00      0.000000      0.000000
2024-11-04 23:45:00+01:00      0.000000      0.000000
2024-11-05 00:00:00+01:00      0.000000      0.000000

### using `data = "watthours"`

In [17]:
node_1 = NodeForecastSolar(
    name="east",
    url="https://api.forecast.solar",
    protocol="forecast_solar",
    api_key="87Fpb6aShqa5Hbmf",
    data="watthours",
    latitude=49.86381,
    longitude=8.68105,
    declination=[14, 10],
    azimuth=[90, -90],
    kwp=[23.31, 23.31],
)


node_2 = NodeForecastSolar(
    name="east",
    url="https://api.forecast.solar",
    protocol="forecast_solar",
    api_key="87Fpb6aShqa5Hbmf",
    data="watthours",
    latitude=49.86381,
    longitude=8.68105,
    declination=[10, 14],
    azimuth=[90, -90],
    kwp=[23.31, 23.31],
)

connector = ForecastSolarConnection(url="https://api.forecast.solar", api_key="87Fpb6aShqa5Hbmf")

nodes = [node_1, node_2]
from_time = datetime.now().replace(hour=0, minute=0, second=0, microsecond=0)
to_time = from_time + timedelta(days=1)
interval = timedelta(minutes=15)

res = connector.read_series(from_time, to_time, nodes, interval)
res

D:\Code Repository\ETA\eta-utility\eta_utility\connectors\forecast_solar.py:147: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  previous_time = from_time.floor("15T") if self._api_key != "None" else from_time.floor("h")
D:\Code Repository\ETA\eta-utility\eta_utility\connectors\forecast_solar.py:154: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  to_time.floor("15T") + timedelta(minutes=15)

                                   east
                                      0             0
2024-11-04 00:00:00+01:00      0.000000      0.000000
2024-11-04 00:15:00+01:00      0.000000      0.000000
2024-11-04 00:30:00+01:00      0.000000      0.000000
2024-11-04 00:45:00+01:00      0.000000      0.000000
2024-11-04 01:00:00+01:00      0.000000      0.000000
2024-11-04 01:15:00+01:00      0.000000      0.000000
2024-11-04 01:30:00+01:00      0.000000      0.000000
2024-11-04 01:45:00+01:00      0.000000      0.000000
2024-11-04 02:00:00+01:00      0.000000      0.000000
2024-11-04 02:15:00+01:00      0.000000      0.000000
2024-11-04 02:30:00+01:00      0.000000      0.000000
2024-11-04 02:45:00+01:00      0.000000      0.000000
2024-11-04 03:00:00+01:00      0.000000      0.000000
2024-11-04 03:15:00+01:00      0.000000      0.000000
2024-11-04 03:30:00+01:00      0.000000      0.000000
2024-11-04 03:45:00+01:00      0.000000      0.000000
2024-11-04 04:00:00+01:00      0.000000      0.000000
2024-11-04 04:15:00+01:00      0.000000      0.000000
2024-11-04 04:30:00+01:00      0.000000      0.000000
2024-11-04 04:45:00+01:00      0.000000      0.000000
2024-11-04 05:00:00+01:00      0.000000      0.000000
2024-11-04 05:15:00+01:00      0.000000      0.000000
2024-11-04 05:30:00+01:00      0.000000      0.000000
2024-11-04 05:45:00+01:00      0.000000      0.000000
2024-11-04 06:00:00+01:00      0.000000      0.000000
2024-11-04 06:15:00+01:00      0.000000      0.000000
2024-11-04 06:30:00+01:00      0.000000      0.000000
2024-11-04 06:45:00+01:00      0.000000      0.000000
2024-11-04 07:00:00+01:00      0.000000      0.000000
2024-11-04 07:15:00+01:00      0.000000      0.000000
2024-11-04 07:30:00+01:00     58.510638     51.723404
2024-11-04 07:45:00+01:00    154.255319    136.361702
2024-11-04 08:00:00+01:00    250.000000    221.000000
2024-11-04 08:15:00+01:00    499.000000    444.000000
2024-11-04 08:30:00+01:00    839.000000    758.000000
2024-11-04 08:45:00+01:00   1243.000000   1144.000000
2024-11-04 09:00:00+01:00   1722.000000   1610.000000
2024-11-04 09:15:00+01:00   2298.000000   2174.000000
2024-11-04 09:30:00+01:00   2985.000000   2849.000000
2024-11-04 09:45:00+01:00   3786.000000   3636.000000
2024-11-04 10:00:00+01:00   4697.000000   4530.000000
2024-11-04 10:15:00+01:00   5705.000000   5518.000000
2024-11-04 10:30:00+01:00   6796.000000   6587.000000
2024-11-04 10:45:00+01:00   7963.000000   7730.000000
2024-11-04 11:00:00+01:00   9202.000000   8946.000000
2024-11-04 11:15:00+01:00  10513.000000  10235.000000
2024-11-04 11:30:00+01:00  11896.000000  11598.000000
2024-11-04 11:45:00+01:00  13348.000000  13032.000000
2024-11-04 12:00:00+01:00  14859.000000  14528.000000
2024-11-04 12:15:00+01:00  16414.000000  16072.000000
2024-11-04 12:30:00+01:00  17999.000000  17649.000000
2024-11-04 12:45:00+01:00  19607.000000  19252.000000
2024-11-04 13:00:00+01:00  21244.000000  20888.000000
2024-11-04 13:15:00+01:00  22938.000000  22584.000000
2024-11-04 13:30:00+01:00  24732.000000  24383.000000
2024-11-04 13:45:00+01:00  26652.000000  26315.000000
2024-11-04 14:00:00+01:00  28687.000000  28372.000000
2024-11-04 14:15:00+01:00  30801.000000  30521.000000
2024-11-04 14:30:00+01:00  32957.000000  32726.000000
2024-11-04 14:45:00+01:00  35124.000000  34959.000000
2024-11-04 15:00:00+01:00  37261.000000  37178.000000
2024-11-04 15:15:00+01:00  39314.000000  39323.000000
2024-11-04 15:30:00+01:00  41242.000000  41353.000000
2024-11-04 15:45:00+01:00  43025.000000  43247.000000
2024-11-04 16:00:00+01:00  44645.000000  44984.000000
2024-11-04 16:15:00+01:00  46098.000000  46553.000000
2024-11-04 16:30:00+01:00  47387.000000  47953.000000
2024-11-04 16:45:00+01:00  48514.000000  49184.000000
2024-11-04 17:00:00+01:00  49419.000000  50176.000000
2024-11-04 17:15:00+01:00  48024.820892  48765.426392
2024-11-04 17:30:00+01:00  46309.648717  47023.804021
2024-11-04 17:45:00+01:00  44594.476543  45282.181650
2024-11-04 18:00:00+01:00  42879.304368  43540.559279
2024-11-04 18:15:00+01:00  41164.132193  41798.936908
2024-11-04 18:30:00+01:00  39448.960018  40057.314537
2024-11-04 18:45:00+01:00  37733.787844  38315.692165
2024-11-04 19:00:00+01:00  36018.615669  36574.069794
2024-11-04 19:15:00+01:00  34303.443494  34832.447423
2024-11-04 19:30:00+01:00  32588.271320  33090.825052
2024-11-04 19:45:00+01:00  30873.099145  31349.202681
2024-11-04 20:00:00+01:00  29157.926970  29607.580310
2024-11-04 20:15:00+01:00  27442.754795  27865.957939
2024-11-04 20:30:00+01:00  25727.582621  26124.335567
2024-11-04 20:45:00+01:00  24012.410446  24382.713196
2024-11-04 21:00:00+01:00  22297.238271  22641.090825
2024-11-04 21:15:00+01:00  20582.066097  20899.468454
2024-11-04 21:30:00+01:00  18866.893922  19157.846083
2024-11-04 21:45:00+01:00  17151.721747  17416.223712
2024-11-04 22:00:00+01:00  15436.549572  15674.601340
2024-11-04 22:15:00+01:00  13721.377398  13932.978969
2024-11-04 22:30:00+01:00  12006.205223  12191.356598
2024-11-04 22:45:00+01:00  10291.033048  10449.734227
2024-11-04 23:00:00+01:00   8575.860874   8708.111856
2024-11-04 23:15:00+01:00   6860.688699   6966.489485
2024-11-04 23:30:00+01:00   5145.516524   5224.867113
2024-11-04 23:45:00+01:00   3430.344349   3483.244742
2024-11-05 00:00:00+01:00   1715.172175   1741.622371

### using `data = "watthoursperperiod"`

In [18]:
node_1 = NodeForecastSolar(
    name="east",
    url="https://api.forecast.solar",
    protocol="forecast_solar",
    api_key="87Fpb6aShqa5Hbmf",
    data="watthoursperperiod",
    latitude=49.86381,
    longitude=8.68105,
    declination=[14, 10],
    azimuth=[90, -90],
    kwp=[23.31, 23.31],
)


node_2 = NodeForecastSolar(
    name="east",
    url="https://api.forecast.solar",
    protocol="forecast_solar",
    api_key="87Fpb6aShqa5Hbmf",
    data="watthoursperperiod",
    latitude=49.86381,
    longitude=8.68105,
    declination=[10, 14],
    azimuth=[90, -90],
    kwp=[23.31, 23.31],
)

connector = ForecastSolarConnection(url="https://api.forecast.solar", api_key="87Fpb6aShqa5Hbmf")

nodes = [node_1, node_2]
from_time = datetime.now().replace(hour=0, minute=0, second=0, microsecond=0)
to_time = from_time + timedelta(days=1)
interval = timedelta(minutes=15)

res = connector.read_series(from_time, to_time, nodes, interval)
res

HTTPError: 404 Client Error: Not Found for url: https://api.forecast.solar/87Fpb6aShqa5Hbmf/estimate/watthoursperperiod/49/8/10/90/23.31/14/-90/23.31?time=utc

#### The URL should be like this [https://api.forecast.solar/87Fpb6aShqa5Hbmf/estimate/watthours/period/49/8/10/90/23.31/14/-90/23.31?time=utc](https://api.forecast.solar/87Fpb6aShqa5Hbmf/estimate/watthours/period/49/8/10/90/23.31/14/-90/23.31?time=utc) 

`watthours/period` instead of `watthoursperperiod`

### using `data = "watthoursperday"`

In [24]:
node_1 = NodeForecastSolar(
    name="east",
    url="https://api.forecast.solar",
    protocol="forecast_solar",
    api_key="87Fpb6aShqa5Hbmf",
    data="watthoursperday",
    latitude=49.86381,
    longitude=8.68105,
    declination=[14, 10],
    azimuth=[90, -90],
    kwp=[23.31, 23.31],
)


node_2 = NodeForecastSolar(
    name="east",
    url="https://api.forecast.solar",
    protocol="forecast_solar",
    api_key="87Fpb6aShqa5Hbmf",
    data="watthoursperday",
    latitude=49.86381,
    longitude=8.68105,
    declination=[10, 14],
    azimuth=[90, -90],
    kwp=[23.31, 23.31],
)

connector = ForecastSolarConnection(url="https://api.forecast.solar", api_key="87Fpb6aShqa5Hbmf")

nodes = [node_1, node_2]
from_time = datetime.now().replace(hour=0, minute=0, second=0, microsecond=0)
to_time = from_time + timedelta(days=1)
interval = timedelta(minutes=15)

res = connector.read_series(from_time, to_time, nodes, interval)
res

HTTPError: 404 Client Error: Not Found for url: https://api.forecast.solar/87Fpb6aShqa5Hbmf/estimate/watthoursperday/49/8/14/90/23.31/10/-90/23.31?time=utc

#### The URL should be like this [https://api.forecast.solar/87Fpb6aShqa5Hbmf/estimate/watthours/day/49/8/14/90/23.31/10/-90/23.31?time=utc](https://api.forecast.solar/87Fpb6aShqa5Hbmf/estimate/watthours/day/49/8/14/90/23.31/10/-90/23.31?time=utc) 

`watthours/day` instead of `watthoursperday`

### `ENTSOEConnection` `NodeEntsoE`

In [23]:
node_e = NodeEntsoE(
    name="entsoe",
    url="https://web-api.tp.entsoe.eu/",
    protocol="entsoe",
    bidding_zone="DEU-LUX",
    endpoint="Price",
)

connector_e = ENTSOEConnection(url="https://web-api.tp.entsoe.eu/", api_token="6311229e-363a-44bd-b827-493aa647a388")

from_time = datetime.now().replace(hour=0, minute=0, second=0, microsecond=0)
to_time = from_time + timedelta(days=1)
interval = timedelta(minutes=15)

res_e = connector_e.read_series(from_time, to_time, node_e, interval)
res_e

                          entsoe_Price
                                    60  15
2024-11-04 00:00:00+01:00        92.04 NaN
2024-11-04 00:15:00+01:00        92.04 NaN
2024-11-04 00:30:00+01:00        92.04 NaN
2024-11-04 00:45:00+01:00        92.04 NaN
2024-11-04 01:00:00+01:00        89.96 NaN
2024-11-04 01:15:00+01:00        89.96 NaN
2024-11-04 01:30:00+01:00        89.96 NaN
2024-11-04 01:45:00+01:00        89.96 NaN
2024-11-04 02:00:00+01:00        90.07 NaN
2024-11-04 02:15:00+01:00        90.07 NaN
2024-11-04 02:30:00+01:00        90.07 NaN
2024-11-04 02:45:00+01:00        90.07 NaN
2024-11-04 03:00:00+01:00        89.86 NaN
2024-11-04 03:15:00+01:00        89.86 NaN
2024-11-04 03:30:00+01:00        89.86 NaN
2024-11-04 03:45:00+01:00        89.86 NaN
2024-11-04 04:00:00+01:00        90.80 NaN
2024-11-04 04:15:00+01:00        90.80 NaN
2024-11-04 04:30:00+01:00        90.80 NaN
2024-11-04 04:45:00+01:00        90.80 NaN
2024-11-04 05:00:00+01:00        98.52 NaN
2024-11-04 05:15:00+01:00        98.52 NaN
2024-11-04 05:30:00+01:00        98.52 NaN
2024-11-04 05:45:00+01:00        98.52 NaN
2024-11-04 06:00:00+01:00       124.89 NaN
2024-11-04 06:15:00+01:00       124.89 NaN
2024-11-04 06:30:00+01:00       124.89 NaN
2024-11-04 06:45:00+01:00       124.89 NaN
2024-11-04 07:00:00+01:00       144.91 NaN
2024-11-04 07:15:00+01:00       144.91 NaN
2024-11-04 07:30:00+01:00       144.91 NaN
2024-11-04 07:45:00+01:00       144.91 NaN
2024-11-04 08:00:00+01:00       139.18 NaN
2024-11-04 08:15:00+01:00       139.18 NaN
2024-11-04 08:30:00+01:00       139.18 NaN
2024-11-04 08:45:00+01:00       139.18 NaN
2024-11-04 09:00:00+01:00       120.63 NaN
2024-11-04 09:15:00+01:00       120.63 NaN
2024-11-04 09:30:00+01:00       120.63 NaN
2024-11-04 09:45:00+01:00       120.63 NaN
2024-11-04 10:00:00+01:00       100.00 NaN
2024-11-04 10:15:00+01:00       100.00 NaN
2024-11-04 10:30:00+01:00       100.00 NaN
2024-11-04 10:45:00+01:00       100.00 NaN
2024-11-04 11:00:00+01:00        97.12 NaN
2024-11-04 11:15:00+01:00        97.12 NaN
2024-11-04 11:30:00+01:00        97.12 NaN
2024-11-04 11:45:00+01:00        97.12 NaN
2024-11-04 12:00:00+01:00        95.16 NaN
2024-11-04 12:15:00+01:00        95.16 NaN
2024-11-04 12:30:00+01:00        95.16 NaN
2024-11-04 12:45:00+01:00        95.16 NaN
2024-11-04 13:00:00+01:00        98.47 NaN
2024-11-04 13:15:00+01:00        98.47 NaN
2024-11-04 13:30:00+01:00        98.47 NaN
2024-11-04 13:45:00+01:00        98.47 NaN
2024-11-04 14:00:00+01:00       103.17 NaN
2024-11-04 14:15:00+01:00       103.17 NaN
2024-11-04 14:30:00+01:00       103.17 NaN
2024-11-04 14:45:00+01:00       103.17 NaN
2024-11-04 15:00:00+01:00       130.40 NaN
2024-11-04 15:15:00+01:00       130.40 NaN
2024-11-04 15:30:00+01:00       130.40 NaN
2024-11-04 15:45:00+01:00       130.40 NaN
2024-11-04 16:00:00+01:00       181.47 NaN
2024-11-04 16:15:00+01:00       181.47 NaN
2024-11-04 16:30:00+01:00       181.47 NaN
2024-11-04 16:45:00+01:00       181.47 NaN
2024-11-04 17:00:00+01:00       290.21 NaN
2024-11-04 17:15:00+01:00       290.21 NaN
2024-11-04 17:30:00+01:00       290.21 NaN
2024-11-04 17:45:00+01:00       290.21 NaN
2024-11-04 18:00:00+01:00       241.04 NaN
2024-11-04 18:15:00+01:00       241.04 NaN
2024-11-04 18:30:00+01:00       241.04 NaN
2024-11-04 18:45:00+01:00       241.04 NaN
2024-11-04 19:00:00+01:00       162.09 NaN
2024-11-04 19:15:00+01:00       162.09 NaN
2024-11-04 19:30:00+01:00       162.09 NaN
2024-11-04 19:45:00+01:00       162.09 NaN
2024-11-04 20:00:00+01:00       123.00 NaN
2024-11-04 20:15:00+01:00       123.00 NaN
2024-11-04 20:30:00+01:00       123.00 NaN
2024-11-04 20:45:00+01:00       123.00 NaN
2024-11-04 21:00:00+01:00       112.27 NaN
2024-11-04 21:15:00+01:00       112.27 NaN
2024-11-04 21:30:00+01:00       112.27 NaN
2024-11-04 21:45:00+01:00       112.27 NaN
2024-11-04 22:00:00+01:00       107.98 NaN
2024-11-04 22:15:00+01:00       107.98 NaN
2024-11-04 22:30:00+01:00       107.98 NaN
2024-11-04 22:45:00+01:00       107.98 NaN
2024-11-04 23:00:00+01:00        97.60 NaN